### ISSUE TITLE
*Suggestion* Add the change directory step to the Installation Guide.

### ISSUE THREAD

**Issue by xNatthapol** [Sankrub/ku-polls#37]
By exactly following the provided installation instructions, the user will get an error in step 4: Install Dependencies.

```cmd
ERROR: Could not open requirements file: [Errno 2] No such file or directory: 'requirements.txt'
```

Also, the Virtual Environment`venv` is not created in the `ku-polls` directory.

Because the user does not change the directory to `ku-polls` after step 1, I suggest adding step 2: Change the directory with `cd ku-polls`.

**Comment by Sankrub** [comment]
done
