### ISSUE TITLE
Get an error 404 Page Not found after navigating directly to the poll detail page, which does not exist.

### ISSUE THREAD

**Issue by xNatthapol** [Sankrub/ku-polls#40]
When I try to navigate directly to a poll detail page `http://localhost:8000/polls/200/` and the poll does not exist, it should `redirect` to the polls index and display an error message on the index page.

**Comment by Sankrub** [comment]
how about the poll that already closed as the requirment do i have to let the user click in to see the choice??

**Comment by xNatthapol** [comment]
Users will be unable to click on and see polls that have already closed.
