### ISSUE TITLE
Cannot set values for externalized variables.

### ISSUE THREAD

**Issue by xNatthapol** [Sankrub/ku-polls#42]
By following to create a .env file in the project root and define the following variables:

```
SECRET_KEY=your_secret_key
DEBUG=True # Set to False for production
DATABASE_URL=your_database_url
```

Then run migrations`python manage.py migrate` and get an error, so I suggest using the command copy:

- On MacOS or Linux
```bash
cp sample.env .env
```

- On Windows
```cmd
copy sample.env .env
```

**Comment by Sankrub** [comment]
okay
